packages: []

allowBuilds:
  '@embedded-postgres/darwin-arm64@17.10.0-beta.17': true
  '@embedded-postgres/darwin-x64@17.10.0-beta.17': true
  '@embedded-postgres/linux-arm64@17.10.0-beta.17': true
  '@embedded-postgres/linux-x64@17.10.0-beta.17': true
  '@prisma/engines@7.9.1': true
  '@scarf/scarf@1.4.0': false
  '@swc/core@1.15.47': true
  'bun@1.4.2': true
  'koffi@3.2.1': true
  'prisma@7.9.1': true
  'sharp@0.34.5': false

minimumReleaseAgeExclude:
  - '@revisium/*'
